version: "3.8"
services:
  redis:
    image: redis:alpine
    command: [ redis-server, --maxmemory 128mb, --maxmemory-policy volatile-lru, --save "" ]
  www_public:
    build:
      context: './sites/www_public/'
#    networks:
#      - frontend_www
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/sites/www_public:/usr/src/app
      - /usr/src/app/node_modules
  php:
    user: ${USER_ID}
    image: pimcore/pimcore:php8.1-debug-latest
    environment:
      COMPOSER_HOME: /var/www/html/
      PHP_IDE_CONFIG: serverName=localhost
#    networks:
#      - backend
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
  supervisord:
    user: ${USER_ID}
    image: pimcore/pimcore:php8.1-supervisord-latest
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
      - ./docker/files/supervisord.conf:/etc/supervisor/conf.d/pimcore.conf:ro
  db:
    image: mariadb:latest
    working_dir: /application
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb-file-per-table=1]
    volumes:
      - pimcore-database:/var/lib/mysql
    environment:
#      - DB_HOST=127.0.0.1
      - MYSQL_ROOT_PASSWORD=ROOT
      - MYSQL_DATABASE=pimcore
      - MYSQL_USER=pimcore
      - MYSQL_PASSWORD=pimcore
#    networks:
#      - backend
    ports:
      - "3306:3306"
  apache:
    build:
      context: './docker/apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      # - mysql
#    networks:
#      - frontend_www
#      - backend
    ports:
      - "80:80"
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
#networks:
#  frontend_www:
#  backend:
volumes:
    pimcore-database:
